task2:
	g++ task2.cpp -o task2.out

task3:
	g++ task3.cpp -o task3.out

task4:
	g++ task4.cpp -o task4.out

task5:
	g++ task5.cpp -o task5.out

task6:
	g++ task6.cpp -o task6.out

task7:
	g++ task7.cpp -o task7.out


clean:
	rm -rf task*.out